### ISSUE TITLE
Path issues in the targets file

### ISSUE THREAD

**Issue by aufder** [Tragedian/Mufu.SpecFlow.DotNetCoreFix#2]
Hi.  We are having 2 issues with the default config in the targets file.  I wonder if this is something you would be ok fixing?
First, this line 79:
      <SpecFlowPackageDir>$(NuGetPackageRoot)@(SpecFlowPackageReference->'%(Identity)\%(Version)')\</SpecFlowPackageDir>
Could benefit from a backslash between $(NuGetPackageRoot) and @(SpecFlowPackageReference.  In our case, $(NuGetPackageRoot) doesn't contain a trailing slash nor does @(SpecFlowPackageReference contain a leading slash.  The fragments concat together and aren't a valid path.  Adding the backslash would fix it.  Windows does appear to handle multiple slashes in a row, or it could be concatenated in code with a slash perhaps.

Also, line 82:
      <GenerateCodeBehindCommand>$(SpecFlowToolsPath)$(SpecFlowToolExe) generateall "$(SpecFlowShadowProject)"</GenerateCodeBehindCommand>
Could benefit from double quotes around the $(SpecFlowToolsPath)$(SpecFlowToolExe).  In our case, the path to the tools contains space chars, which then lead to an error when the command runs.  Containing the full command path in double quotes fixes the problem.

Thanks for considering these changes.
Alan

**Comment by Code-Grump** [comment]
Since there are two errors reported here, I've split them into issues #3 and #4. I'd like to continue discussion there.
