### ISSUE TITLE
Error detecting Specflow tools version when NuGetPackageRoot does not have trailing slash

### ISSUE THREAD

**Issue by Code-Grump** [Tragedian/Mufu.SpecFlow.DotNetCoreFix#4]
First, this line 79:
$(NuGetPackageRoot)@(SpecFlowPackageReference->'%(Identity)%(Version)')</SpecFlowPackageDir>
Could benefit from a backslash between $(NuGetPackageRoot) and @(SpecFlowPackageReference. In our case, $(NuGetPackageRoot) doesn't contain a trailing slash nor does @(SpecFlowPackageReference contain a leading slash. The fragments concat together and aren't a valid path. Adding the backslash would fix it. Windows does appear to handle multiple slashes in a row, or it could be concatenated in code with a slash perhaps.

**Comment by Code-Grump** [comment]
There's a convention in MSBuild that Path variables end with a trailing slash, specifically to avoid this kind of problem. Are you overriding the NuGetPackageRoot variable in your build?

The accepted way of handling deviations from this is to make a call to `Path.Combine`, but I've not tried mixing a CLR method-call with a transform.

**Comment by aufder** [comment]
Our NuGet.Config does contain:
      add key="globalPackagesFolder" value="packages" 
However, even if I add a trailing slash there, it doesn't show up when the command executes.

Not sure where to look for the  NuGetPackageRoot setting to know if it is overridden.

**Comment by Code-Grump** [comment]
It's a property created by NuGet when you build your application. If you check in your `\obj` folder, you should see a file called `<your-project-name>.csproj.nuget.g.props`. If you look in there, you should see a line like:

    <NuGetPackageRoot` Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>

Do you see this file, or anything in there which might indicate a problem?

**Comment by aufder** [comment]
In there is:
`<NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">C:\blah\packages</NuGetPackageRoot>`
With blah being my full path.

**Comment by aufder** [comment]
Later in the file are things like this, which appear to presume that NuGetPackageRoot doesn't have a trailing slash:
`    <Import Project="$(NuGetPackageRoot)\mstest.testadapter\1.2.0\build\netcoreapp1.0\MSTest.TestAdapter.props" Condition="Exists('$(NuGetPackageRoot)\mstest.testadapter\1.2.0\build\netcoreapp1.0\MSTest.TestAdapter.props')" />
    <Import Project="$(NuGetPackageRoot)\microsoft.net.test.sdk\15.5.0\build\netcoreapp1.0\Microsoft.Net.Test.Sdk.props" Condition="Exists('$(NuGetPackageRoot)\microsoft.net.test.sdk\15.5.0\build\netcoreapp1.0\Microsoft.Net.Test.Sdk.props')" />
`

**Comment by Code-Grump** [comment]
I've never looked deeply into this property file until now; I don't have any of those extra slashes in my test environments either. I'll have to check around to see why this behaviour is different for you and what expected handling is in place by other projects.

**Comment by aufder** [comment]
To build on that further, we needed to have the packages folder in our project, instead of in $(UserProfile)... because in order for specflow with .net core to function for us, we had to have a DLL reference to the specflow DLL.  Otherwise, we could not run the tests. 
Given that each user and the build box will have the 'users' packages folder in a different spot, we need to have them in the project packages folder.  Hope that makes sense.

**Comment by aufder** [comment]
That's what the comment above about the globalPackagesFolder is related to.

**Comment by Code-Grump** [comment]
If your only issue was with Specflow, you shouldn't need to have the package cache anywhere non-standard. Not that you shouldn't have the freedom to put that path wherever you please, but it's very strange to see NuGet generate a path without a suffix.

If you take out your custom path from the config, does it still cause you problems?

I don't see any special handling of this path from the other projects I've looked into; they seem to assume it follows standard MSBuild conventions.

**Comment by aufder** [comment]
It is strange.  We actually cannot build our specflow project, unless we do a specific DLL reference in the project to the TechTalk.SpecFlow.DLL in its path on disk.
We get errors like this:
`blah.feature.cs(15,11,15,19): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)`
And yes, the TechTalk.SpecFlow NuGet was added to the project via package manager.  I think we found others commenting on the same issue, so we simply add a hard reference to the DLL and it works.
In order for the hard reference to be portable, we need that package in our project packages folder.

We are hoping someday to remove this dependency, but we are just trying to get things working.  And your project definitely helped us.  Thanks.

**Comment by Code-Grump** [comment]
To directly address the issue you've been having, have you followed *all* the steps from the readme?

https://github.com/Tragedian/Mufu.SpecFlow.DotNetCoreFix/blob/develop/README.md

Forgive me for asking, but there is some non-obvious stuff in there that's easy to miss if you've just picked up the package. I'm wondering if NuGet could either make some of these changes to the project happen automatically, or just open a readme when you first install the package.

Back to the topic of a custom NuGet path: it shouldn't be hard to support the lack of a trailing slash. A simple fix would be to add the trailing slash to the property, if it doesn't already have one:

    <NuGetPackageRoot Condition="!HasTrailingSlash('$(NuGetPackageRoot)')">$(NuGetPackageRoot)\</NuGetPackageRoot>

**Comment by aufder** [comment]
In our haste I think we missed your README.  I just did that, and I still have the same compilation errors when I don't reference the TechTalk.SpecFlow.DLL:
`6>------ Rebuild All started: Project: Spr.Specs, Configuration: Debug Any CPU ------
6>StepDefinitions.cs(10,7,10,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
6>StepDefinitions.cs(11,7,11,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
6>TestHooks.cs(2,7,2,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
`
So for now I need to continue adding the DLL reference.

I will try the trailing slash proposal you mention and see how that works.  Where (what file/config/proj...) exactly would I put that statement?

**Comment by Code-Grump** [comment]
The change would have to happen around here: https://github.com/Tragedian/Mufu.SpecFlow.DotNetCoreFix/blob/develop/src/Mufu.SpecFlow.DotNetCoreFix/build/Mufu.SpecFlow.DotNetCoreFix.targets#L77

You can try a modification in your local version of the .targets file, if you're feeling adventurous.

**Comment by aufder** [comment]
Right.  The problem then is each dev would have to do the same change on their boxes, and we'd have to also do it on the package folder on the build boxes.
If I can't come up with a solution to the trailing slash, I'll have to run with a patched version of the package that all my boxes can fetch.
I will keep trying, but may take time.
Thanks for your help on this.

**Comment by aufder** [comment]
Got it.  So I just did this to try it out.
`      <NuGetPackageRoot Condition="!HasTrailingSlash('$(NuGetPackageRoot)')">$(NuGetPackageRoot)\</NuGetPackageRoot>      
      <SpecFlowPackageDir>$(NuGetPackageRoot)@(SpecFlowPackageReference->'%(Identity)\%(Version)')\</SpecFlowPackageDir>
`
Adding your HasTrailingSlash proposal, and it does work for that.
Still though, unless you are able to add that in formally, I would have to run with a patched package everywhere.
Thanks

**Comment by Code-Grump** [comment]
If you feel you have the time, you're welcome to submit a pull request with your fix.

**Comment by Code-Grump** [comment]
I've published a new version of the package with a fix for this issue. @aufder I would appreciate if you could check to see if it works for your situation.

https://www.nuget.org/packages/Mufu.SpecFlow.DotNetCoreFix/1.0.3-alpha

**Comment by aufder** [comment]
Hi, yes, it does work for me.  Thank you for making those changes!
